---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dep-httpd
  labels:
    app: apache_webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      component: httpd
  template:
    metadata:
      labels:
        component: httpd
    spec:
      affinity:
        podAntiAffinity:                                       # Just need to change this line to do the reverse
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  component: mysql_db_server
              topologyKey: kubernetes.io/hostname
      containers:
        - name: cntr-httpd
          image: httpd:latest
          ports:
            - containerPort: 80
